# tests/BUILD
cc_test(
    name = "math_util_test",
    srcs = ["math_util_test.cc"],
    deps = [
        "//:math_util",
        "@com_google_googletest//:gtest_main",
    ],
    copts = ["-std=c++17"],
)
