"""
Output layer for AI Lab Platform.

Provides structured report generation and multiple output formats (Markdown, HTML, JSON).
Supports report metadata, sections, and distribution capabilities.
"""

import json
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any

from utils.logger import get_logger

logger = get_logger(__name__)

# Streamlit is optional (for UI features)
try:
    import streamlit as st
    HAS_STREAMLIT = True
except ImportError:
    HAS_STREAMLIT = False
    st = None  # type: ignore


class ReportFormat(Enum):
    """Supported report output formats."""
    MARKDOWN = "md"
    HTML = "html"
    JSON = "json"


@dataclass
class ReportMetadata:
    """Metadata for a generated report."""
    title: str
    created_at: datetime = field(default_factory=datetime.now)
    author: str = "AI Lab Platform"
    version: str = "1.0"
    tags: list[str] = field(default_factory=list)
    source: str | None = None
    
    def to_dict(self) -> dict[str, Any]:
        """Convert metadata to dictionary."""
        return {
            "title": self.title,
            "created_at": self.created_at.isoformat(),
            "author": self.author,
            "version": self.version,
            "tags": self.tags,
            "source": self.source,
        }


@dataclass
class ReportSection:
    """A section within a report."""
    title: str
    content: str
    order: int = 0
    metadata: dict[str, Any] = field(default_factory=dict)
    
    def to_markdown(self) -> str:
        """Convert section to Markdown format."""
        return f"## {self.title}\n\n{self.content}\n"
    
    def to_html(self) -> str:
        """Convert section to HTML format."""
        escaped_content = self.content.replace("<", "&lt;").replace(">", "&gt;")
        return f"<section>\n<h2>{self.title}</h2>\n<p>{escaped_content}</p>\n</section>\n"


@dataclass
class Report:
    """
    Structured report with metadata and sections.
    
    Attributes:
        metadata: Report metadata
        sections: List of report sections
        raw_content: Optional raw content string
        data: Additional data dictionary
    """
    metadata: ReportMetadata
    sections: list[ReportSection] = field(default_factory=list)
    raw_content: str | None = None
    data: dict[str, Any] = field(default_factory=dict)
    
    def add_section(self, section: ReportSection) -> None:
        """Add a section to the report."""
        self.sections.append(section)
        self.sections.sort(key=lambda s: s.order)
    
    def to_markdown(self) -> str:
        """Convert entire report to Markdown format."""
        lines: list[str] = [
            f"# {self.metadata.title}\n",
            f"*Generated by {self.metadata.author} on {self.metadata.created_at.strftime('%Y-%m-%d %H:%M')}*\n",
        ]
        
        if self.raw_content:
            lines.append(self.raw_content)
        else:
            for section in self.sections:
                lines.append(section.to_markdown())
        
        return "\n".join(lines)
    
    def to_html(self) -> str:
        """Convert entire report to HTML format."""
        sections_html = "\n".join(
            section.to_html() for section in self.sections
        ) if self.sections else f"<p>{self.raw_content or ''}</p>"
        
        return f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{self.metadata.title}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; line-height: 1.6; }}
        h1 {{ color: #333; border-bottom: 2px solid #0066cc; padding-bottom: 0.5rem; }}
        h2 {{ color: #444; margin-top: 2rem; }}
        section {{ margin: 2rem 0; }}
        .meta {{ color: #666; font-size: 0.9rem; margin-bottom: 2rem; }}
        code {{ background: #f4f4f4; padding: 0.2rem 0.4rem; border-radius: 3px; }}
        pre {{ background: #f4f4f4; padding: 1rem; border-radius: 5px; overflow-x: auto; }}
        table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
        th, td {{ border: 1px solid #ddd; padding: 0.5rem; text-align: left; }}
        th {{ background: #f4f4f4; }}
    </style>
</head>
<body>
    <h1>{self.metadata.title}</h1>
    <div class="meta">Generated by {self.metadata.author} on {self.metadata.created_at.strftime('%Y-%m-%d %H:%M')}</div>
    {sections_html}
</body>
</html>"""
    
    def to_json(self) -> str:
        """Convert report to JSON format."""
        data = {
            "metadata": self.metadata.to_dict(),
            "sections": [
                {
                    "title": s.title,
                    "content": s.content,
                    "order": s.order,
                    "metadata": s.metadata,
                }
                for s in self.sections
            ],
            "raw_content": self.raw_content,
            "data": self.data,
        }
        return json.dumps(data, indent=2, ensure_ascii=False)
    
    def to_dict(self) -> dict[str, Any]:
        """Convert report to dictionary."""
        return {
            "metadata": self.metadata.to_dict(),
            "sections": [
                {
                    "title": s.title,
                    "content": s.content,
                    "order": s.order,
                }
                for s in self.sections
            ],
            "raw_content": self.raw_content,
            "data": self.data,
        }


class OutputHandler(ABC):
    """Abstract base class for output handlers."""
    
    @abstractmethod
    def handle(self, report: Report, format: ReportFormat) -> dict[str, Any]:
        """
        Handle report output.
        
        Args:
            report: The report to output
            format: Output format
            
        Returns:
            Result dictionary with success status and metadata
        """
        pass


class FileOutputHandler(OutputHandler):
    """Output handler for file output."""
    
    def __init__(self, output_dir: Path | None = None):
        """
        Initialize file output handler.
        
        Args:
            output_dir: Directory for output files (defaults to current directory)
        """
        self.output_dir = output_dir or Path.cwd()
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def handle(self, report: Report, format: ReportFormat) -> dict[str, Any]:
        """Save report to file."""
        try:
            filename = f"{report.metadata.title.replace(' ', '_').lower()}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.{format.value}"
            filepath = self.output_dir / filename
            
            match format:
                case ReportFormat.MARKDOWN:
                    filepath.write_text(report.to_markdown(), encoding="utf-8")
                case ReportFormat.HTML:
                    filepath.write_text(report.to_html(), encoding="utf-8")
                case ReportFormat.JSON:
                    filepath.write_text(report.to_json(), encoding="utf-8")
            
            logger.info("report_saved", filepath=str(filepath), format=format.value)
            return {"success": True, "filepath": str(filepath), "handler": "file"}
        except Exception as e:
            logger.error("file_output_failed", error=str(e))
            return {"success": False, "error": str(e), "handler": "file"}


class StreamlitOutputHandler(OutputHandler):
    """Output handler for Streamlit display."""
    
    def handle(self, report: Report, format: ReportFormat) -> dict[str, Any]:
        """Display report in Streamlit."""
        if not HAS_STREAMLIT:
            return {"success": False, "error": "Streamlit not available", "handler": "streamlit"}
        
        try:
            match format:
                case ReportFormat.MARKDOWN:
                    st.markdown(report.to_markdown())
                case ReportFormat.HTML:
                    st.html(report.to_html())
                case ReportFormat.JSON:
                    st.json(report.to_dict())
            
            return {"success": True, "handler": "streamlit"}
        except Exception as e:
            logger.error("streamlit_output_failed", error=str(e))
            return {"success": False, "error": str(e), "handler": "streamlit"}


class DownloadOutputHandler(OutputHandler):
    """Output handler for Streamlit download button."""
    
    def handle(self, report: Report, format: ReportFormat, filename: str | None = None) -> dict[str, Any]:
        """Create download button in Streamlit."""
        if not HAS_STREAMLIT:
            return {"success": False, "error": "Streamlit not available", "handler": "download"}
        
        try:
            match format:
                case ReportFormat.MARKDOWN:
                    data = report.to_markdown()
                    mime = "text/markdown"
                    ext = "md"
                case ReportFormat.HTML:
                    data = report.to_html()
                    mime = "text/html"
                    ext = "html"
                case ReportFormat.JSON:
                    data = report.to_json()
                    mime = "application/json"
                    ext = "json"
            
            download_filename = filename or f"{report.metadata.title.replace(' ', '_').lower()}.{ext}"
            
            st.download_button(
                label=f"📥 Download {format.value.upper()}",
                data=data,
                file_name=download_filename,
                mime=mime,
                use_container_width=True,
            )
            
            return {"success": True, "handler": "download"}
        except Exception as e:
            logger.error("download_output_failed", error=str(e))
            return {"success": False, "error": str(e), "handler": "download"}


def create_stock_report(
    ticker: str,
    company_name: str,
    content: str,
    title: str | None = None,
    data: dict[str, Any] | None = None
) -> Report:
    """
    Create a stock analysis report.
    
    Args:
        ticker: Stock ticker symbol
        company_name: Company name
        content: Report content (markdown)
        title: Optional custom title
        data: Optional additional data
        
    Returns:
        Structured Report instance
    """
    metadata = ReportMetadata(
        title=title or f"{ticker} Investment Analysis",
        source=f"yfinance/{ticker}",
        tags=["stock", "analysis", ticker.lower()],
    )
    
    return Report(
        metadata=metadata,
        raw_content=content,
        data=data or {},
    )


def quick_output(
    report: Report,
    format: ReportFormat = ReportFormat.MARKDOWN,
    filename: str | None = None,
    show_streamlit: bool = True,
    show_download: bool = True,
    save_to_file: bool = False,
    output_dir: Path | None = None
) -> dict[str, Any]:
    """
    Quick output a report to multiple destinations.
    
    Args:
        report: The report to output
        format: Output format
        filename: Optional filename for download
        show_streamlit: Whether to display in Streamlit
        show_download: Whether to show download button
        save_to_file: Whether to save to file
        output_dir: Directory for file output
        
    Returns:
        Combined result dictionary
    """
    results: list[dict[str, Any]] = []
    
    if show_streamlit and HAS_STREAMLIT:
        handler = StreamlitOutputHandler()
        results.append(handler.handle(report, format))
    
    if show_download and HAS_STREAMLIT:
        handler = DownloadOutputHandler()
        results.append(handler.handle(report, format, filename))
    
    if save_to_file:
        handler = FileOutputHandler(output_dir)
        results.append(handler.handle(report, format))
    
    # Combine results
    success = all(r.get("success", False) for r in results)
    errors = [r.get("error") for r in results if r.get("error")]
    
    return {
        "success": success,
        "results": results,
        "errors": errors,
    }
