set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
find_package(Threads REQUIRED)
add_library(cclab_portable STATIC src/common/consistent_hash/consistent_hash.cc)
target_include_directories(cclab_portable PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/src")
target_link_libraries(cclab_portable PUBLIC Threads::Threads)
xlab_target_defaults(cclab_portable)

add_executable(cclab src/main.cc)
target_link_libraries(cclab PRIVATE cclab_portable)

if(BUILD_TESTING)
    xlab_require_googletest()
    include(GoogleTest)
    foreach(component consistent_hash enum double column)
        add_executable(cclab_${component}_test "test/common/${component}_test.cc")
        target_link_libraries(cclab_${component}_test PRIVATE cclab_portable GTest::gtest_main)
        xlab_target_defaults(cclab_${component}_test)
        gtest_discover_tests(cclab_${component}_test DISCOVERY_MODE PRE_TEST
            PROPERTIES TIMEOUT 60)
    endforeach()
    add_executable(cclab_defer_test test/utils/defer_test.cc)
    target_link_libraries(cclab_defer_test PRIVATE cclab_portable GTest::gtest)
    xlab_target_defaults(cclab_defer_test)
    gtest_discover_tests(cclab_defer_test DISCOVERY_MODE PRE_TEST PROPERTIES TIMEOUT 60)
endif()
