#!/usr/bin/env python3
"""Mock API server for testing the research pipeline."""
import json
from http.server import HTTPServer, BaseHTTPRequestHandler


class MockHandler(BaseHTTPRequestHandler):
    def do_POST(self):
        if self.path == "/chat/completions":
            content_length = int(self.headers.get("Content-Length", 0))
            body = self.rfile.read(content_length)
            request = json.loads(body)
            
            model = request.get("model", "unknown")
            messages = request.get("messages", [])
            user_msg = messages[-1].get("content", "") if messages else ""
            
            # Extract product name from user message
            product = "LLM API Product"
            if "report for:" in user_msg:
                product = user_msg.split("report for:")[-1].strip()
            
            response = {
                "id": "mock-research-report",
                "object": "chat.completion",
                "created": 1234567890,
                "model": model,
                "choices": [{
                    "index": 0,
                    "message": {
                        "role": "assistant",
                        "content": f"""# Deep Research Report: {product}

## Executive Summary

This is a comprehensive analysis of {product}, covering its technical capabilities, pricing structure, and competitive positioning in the LLM API market.

## Product Overview

**Provider**: Leading AI company
**Model Family**: Advanced LLM series
**Core Capabilities**: Text generation, code completion, reasoning

## Technical Deep Dive

### Architecture
- Transformer-based architecture
- Advanced attention mechanisms
- Optimized inference pipeline

### Context Window
- Input: Up to 128K tokens
- Output: Up to 4K tokens

## API & Developer Experience

| Feature | Details |
|---------|---------|
| Authentication | API Key |
| SDKs | Python, Node.js, Go |
| Rate Limits | 1000 req/min |

## Competitive Positioning

### SWOT Analysis

| Strengths | Weaknesses |
|-----------|------------|
| High accuracy | Higher latency |
| Good documentation | Limited fine-tuning |

| Opportunities | Threats |
|---------------|---------|
| Enterprise growth | Price competition |

## Pricing

| Tier | Price per 1M tokens |
|------|---------------------|
| Input | $0.50 |
| Output | $1.50 |

## Analyst Verdict

**Overall Score: 8.5/10**

- Capability: 9/10
- Developer Experience: 8/10
- Pricing: 8/10
- Ecosystem: 9/10
- Innovation: 8/10

**Recommendation**: Highly recommended for production use cases requiring high accuracy and reliability.

---
*Generated by Mock API for testing purposes*
"""
                    },
                    "finish_reason": "stop"
                }]
            }
            
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.end_headers()
            self.wfile.write(json.dumps(response).encode())
        else:
            self.send_response(404)
            self.end_headers()
    
    def log_message(self, format, *args):
        # Suppress logs
        pass


if __name__ == "__main__":
    server = HTTPServer(("localhost", 9999), MockHandler)
    print("Mock API server running on http://localhost:9999")
    server.serve_forever()
