CXX = g++
# CXXFLAGS = -std=c++17 -O0 -fno-omit-frame-pointer -g
CXXFLAGS = -std=c++17 -O2
BIN_DIR = bin

leetcode_3318: src/leetcode/leetcode_3318.cc
	$(CXX) $(CXXFLAGS) -o $(BIN_DIR)/leetcode_3318 src/leetcode/leetcode_3318.cc

leetcode_3321: src/leetcode/leetcode_3321.cc
	$(CXX) $(CXXFLAGS) -o $(BIN_DIR)/leetcode_3321 src/leetcode/leetcode_3321.cc

leetcode_3607: src/leetcode/leetcode_3607.cc
	$(CXX) $(CXXFLAGS) -o $(BIN_DIR)/leetcode_3607 src/leetcode/leetcode_3607.cc

leetcode_1611: src/leetcode/leetcode_1611.cc
	$(CXX) $(CXXFLAGS) -o $(BIN_DIR)/leetcode_1611 src/leetcode/leetcode_1611.cc

leetcode_2169: src/leetcode/leetcode_2169.cc
	$(CXX) $(CXXFLAGS) -o $(BIN_DIR)/leetcode_2169 src/leetcode/leetcode_2169.cc

leetcode_3541: src/leetcode/leetcode_3541.cc
	$(CXX) $(CXXFLAGS) -o $(BIN_DIR)/leetcode_3541 src/leetcode/leetcode_3541.cc

leetcode_3228: src/leetcode/leetcode_3228.cc
	$(CXX) $(CXXFLAGS) -o $(BIN_DIR)/leetcode_3228 src/leetcode/leetcode_3228.cc

leetcode_2536: src/leetcode/leetcode_2536.cc
	$(CXX) $(CXXFLAGS) -o $(BIN_DIR)/leetcode_2536 src/leetcode/leetcode_2536.cc

leetcode_3234: src/leetcode/leetcode_3234.cc
	$(CXX) $(CXXFLAGS) -o $(BIN_DIR)/leetcode_3234 src/leetcode/leetcode_3234.cc

leetcode_1513: src/leetcode/leetcode_1513.cc
	$(CXX) $(CXXFLAGS) -o $(BIN_DIR)/leetcode_1513 src/leetcode/leetcode_1513.cc

clean:
	rm -f $(BIN_DIR)/*