CXX = g++
CXXFLAGS = -std=c++17 -O0 -fno-omit-frame-pointer -g
BIN_DIR = bin

leetcode_3318: src/leetcode/leetcode_3318.cc
	$(CXX) $(CXXFLAGS) -o $(BIN_DIR)/leetcode_3318 src/leetcode/leetcode_3318.cc

leetcode_3321: src/leetcode/leetcode_3321.cc
	$(CXX) $(CXXFLAGS) -o $(BIN_DIR)/leetcode_3321 src/leetcode/leetcode_3321.cc

leetcode_3607: src/leetcode/leetcode_3607.cc
	$(CXX) $(CXXFLAGS) -o $(BIN_DIR)/leetcode_3607 src/leetcode/leetcode_3607.cc

leetcode_1611: src/leetcode/leetcode_1611.cc
	$(CXX) $(CXXFLAGS) -o $(BIN_DIR)/leetcode_1611 src/leetcode/leetcode_1611.cc

leetcode_2169: src/leetcode/leetcode_2169.cc
	$(CXX) $(CXXFLAGS) -o $(BIN_DIR)/leetcode_2169 src/leetcode/leetcode_2169.cc

clean:
	rm -f $(BIN_DIR)/*