"""User profile model for storing AI-generated user profiles."""

import uuid

from sqlalchemy import Column, ForeignKey, String, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship
from sqlalchemy.types import JSON

from app.models.base import Base, GUID, TimestampMixin


class UserProfile(Base, TimestampMixin):
    """User profile model for AI-generated user profiles.

    Stores the global profile and role-specific profiles generated by AI
    based on user's daily records and interactions.

    Attributes:
        id: UUID primary key.
        user_id: Reference to the User (one-to-one).
        role_id: Current active role identifier (e.g., 'therapist', 'coach').
        global_profile: The main profile text shared across all roles.
        role_profiles: JSON object storing role-specific profile data.
            Format: {"therapist": "...", "coach": "...", ...}

    Relationships:
        user: Reference back to the User model.
    """

    __tablename__ = "user_profiles"

    id = Column(
        GUID(),
        primary_key=True,
        default=uuid.uuid4,
    )
    user_id = Column(
        GUID(),
        ForeignKey("users.id", ondelete="CASCADE"),
        unique=True,
        nullable=False,
    )
    role_id = Column(
        String(50),
        default="therapist",
    )
    global_profile = Column(Text)
    role_profiles = Column(
        JSON().with_variant(JSONB, "postgresql"),
        default=dict,
    )

    # Relationships
    user = relationship("User", back_populates="profile")